//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipoUnico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EquipoUnico()
        {
            this.prestamo = new HashSet<Prestamo>();
        }

        public int ID_Equipo { get; set; }
        public string Num_Serie { get; set; }
        public bool Activo { get; set; }
        public int Tipo_ArticuloID_Articulo { get; set; }
        public int Inventario_LabID_Lab { get; set; }


        public virtual Inventario_Lab Inventario_Lab { get; set; }
        public virtual Tipo_Articulo Tipo_Articulo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prestamo> prestamo { get; set; }


    }
}
