//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prestamo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Prestamo()
        {
            this.Registro_Estados = new HashSet<Registro_Estados>();
        }
    
        public int ID_Prestamo { get; set; }
        public int EquipoUnicoID_Equipo { get; set; }
        public int UsuarioID_User { get; set; }
        public string Date_Entrega { get; set; }
        public string Date_Vencimiento { get; set; }
    
        public virtual EquipoUnico EquipoUnico { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Registro_Estados> Registro_Estados { get; set; }

    }
}
