//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.sgi_bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nav_EstadoPrestamo
    {
        public int ID_Seguimiento_Estado { get; set; }
        public int PrestamoID_Prestamo { get; set; }
        public int EstadosID_Estado { get; set; }
    
        public virtual Prestamo Prestamo { get; set; }
        public virtual Estados Estados { get; set; }
    }
}
