//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.sgi_bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prestamo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Prestamo()
        {
            this.Nav_EstadoPrestamo = new HashSet<Nav_EstadoPrestamo>();
        }
    
        public int ID_Prestamo { get; set; }
        public System.DateTime Date_Entrega { get; set; }
        public System.DateTime Date_Vencimiento { get; set; }
        public System.DateTime Date_Devolucion { get; set; }
        public int EquipoUnicoID_Serie { get; set; }
        public int UsuarioID { get; set; }
    
        public virtual EquipoUnico EquipoUnico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nav_EstadoPrestamo> Nav_EstadoPrestamo { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
