//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.sgi_bd
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SGI_bdContainer : DbContext
    {
        public SGI_bdContainer()
            : base("name=SGI_bdContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Inventario_Carrera> Inventario_Carrera { get; set; }
        public virtual DbSet<EquipoUnico> EquipoUnico { get; set; }
        public virtual DbSet<Tipo_Articulo> Tipo_Articulo { get; set; }
        public virtual DbSet<Prestamo> Prestamo { get; set; }
        public virtual DbSet<Nav_EstadoPrestamo> Nav_EstadoPrestamo { get; set; }
        public virtual DbSet<Estados> Estados { get; set; }
        public virtual DbSet<Carrera_Usuario> Carrera_Usuario { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
